const mongoose = require('mongoose');
const Champion = mongoose.Schema({
    CiudadR:{
        type:String,
        required:true
    },
    DireccionR:{
        type:String,
        required:true
    },
    NombreD:{
        type:String,
        required:true
    },
    CedulaD:{
        type:String,
        required:true
    },
    CiudadD:{
        type:String,
        required:true
    },
    DireccionD:{
        type:String,
        required:true
    },
    Fecha:{
        type:String,
        required:true
    },
    Hora:{
        type:String,
        required:true
    },
    Alto:{
        type:String,
        required:true
    },
    Ancho:{
        type:String,
        required:true
    },
    Largo:{
        type:String,
        required:true
    },
    Peso:{
        type:String,
        required:true
    }
})